### ISSUE TITLE
Bug in initializing SortedSet with lambda key in list comprehension?

### ISSUE THREAD

**Issue by erikcs** [grantjenks/python-sortedcontainers#129]
Consider the following

```python
from sortedcontainers import SortedSet

def cmp(val, i):
    return val**i

values = [0, 2, -10, 5]
    
s = SortedSet(values, lambda x: cmp(x, 1))
s
# SortedSet([-10, 0, 2, 5], key=<function <lambda> at 0x112cf2ea0>)

# And its copy
s.copy()
# SortedSet([-10, 0, 2, 5], key=<function <lambda> at 0x112cf2ea0>)
```

Now look at the same sorted set of values according to comparison key `i=1` and its copy, but initialized in a list comprehension:

```python
sorted_sets = [SortedSet(values, lambda x: cmp(x, i)) for i in range(3)]

sorted_sets[1]
# SortedSet([-10, 0, 2, 5], key=<function <listcomp>.<lambda> at 0x114a47bf8>)

sorted_sets[1].copy()
# SortedSet([0, 2, 5, -10], key=<function <listcomp>.<lambda> at 0x114a47bf8>)
```

As you see, the order in `sorted_sets[1].copy()` is wrong.

My version info:

```python
import sys
print(sys.version)
3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
# sortedcontainers  2.1.0
```

**Comment by grantjenks** [comment]
The lambda keyword creates a function which forms a closure over the variable “i”. Python’s closures are by reference, not by value. At the time sorted_sets[1] is created the value of “i” is 1. But at the time sorted_sets[1] is copied, the value of “i” is 2. Your key function is technically invalid because it returns different values at different times for the same key.

**Comment by grantjenks** [comment]
This may be a helpful dialogue: https://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture

**Comment by erikcs** [comment]
Ooooh! Thank you very much! This was very educational.
