### ISSUE TITLE
Any plan to get this into standard library?

### ISSUE THREAD

**Issue by bobfang1992** [grantjenks/python-sortedcontainers#160]
Hi, it feels that this package deserves a place in the standard library, do you have any plan to draft an PEP and get this merged into the standard library?

Thanks!

**Comment by grantjenks** [comment]
I’ve talked about it with a couple of core committers but haven’t been too motivated to do so.

Is there some reason PyPI doesn’t work?

**Comment by bobfang1992** [comment]
Thanks for getting back to me! Pypi works but it would be nice to have this without going the extra step of `pip install`. 

The package is small and self-contained and I see no reason why Python cannot have it as a standard library module unless the core guys want this to be implemented in C first (which I imagine would involve some non-trivial work). 

Anyway, this is just a kind suggestion from a fan of your work. Let me know if I can be any help if you ever decide to do this.

**Comment by grantjenks** [comment]
Thanks!

**Comment by ghTempAcc** [comment]
> Is there some reason PyPI doesn’t work?

I never use python when writing algorithmic code. *Except* when I am interviewing. A lot of interview sandboxes now have this library installed but since it's third party, you still have to go through a dance to justify it to your interviewer. If you use  C++ or java, you don't have this problem (they have std::set and TreeSet in their standard library, though SortedList is even more powerful since it handles multiset and get by index too).

Example problem that is really short to do with a sorted list data structure but pretty much impossible if you had to code from scratch: https://leetcode.com/problems/count-of-range-sum/

```
from sortedcontainers import SortedList

class Solution:
    def countRangeSum(self, nums: List[int], lower: int, upper: int) -> int:
        count = 0
        prefix = 0
        seen = SortedList([0])
        for x in nums:
            prefix += x
            count += seen.bisect_right(prefix - lower) - seen.bisect_left(prefix - upper)
            seen.add(prefix)
        return count
```
