### ISSUE TITLE
Doc template is missing from PyPI tarball

### ISSUE THREAD

**Issue by QuLogic** [grantjenks/python-sortedcontainers#91]
If you download the 2.0.1 tarball from PyPI and attempt to build the docs from it, it will fail with a `TemplateNotFound` exception. This appears to be because the `docs/_templates` directory is not included.

**Comment by grantjenks** [comment]
I’m not sure how to include that. Does the zipball or tarball from Github work instead? The releases are tagged, if that helps.

I’d prefer to keep the source distribution as small as possible. What do you use the source distro for other than installing the package?

**Comment by grantjenks** [comment]
First, thank you for building packages for Fedora!

Second, I tried to do as you suggested and had it working at one point but then messed it up ... :(  The source distribution that I now build only includes the sources themselves, not the tests or docs directories. I think it's actually better this way because the wheel/source download from PyPI is smaller and I didn't really intend to ship the tests and docs directories (they are unnecessary for an installation).

If you really want to publish the html docs along with the package then please use the Github zipball. I tag releases so it should be easy to access at something like:

    https://github.com/grantjenks/python-sortedcontainers/archive/v2.0.2.zip

Sorry I broke the way it worked before but I think using Github is a better option going forward.

**Comment by QuLogic** [comment]
I can get by with GitHub tarballs, but just wanted to point out that the PyPI tarball does _not_ exclude tests and docs.

**Comment by grantjenks** [comment]
Thanks for your flexibility.

In v2.0.3 the PyPI tarballs *will* exclude tests and docs.

**Comment by grantjenks** [comment]
@QuLogic, you may want to follow Issue #37 for updates. I use that issue to communicate with the Debian package maintainer.
