### ISSUE TITLE
Dropping iter* breaks Python 2 compatability

### ISSUE THREAD

**Issue by bucko909** [grantjenks/python-sortedcontainers#94]
On python 2:

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sortedcontainers
>>> sortedcontainers.SortedDict.iteritems
<method 'iteritems' of 'dict' objects>
```

After removing these functions, your code now falls back to the *unsorted* implementation from the default `dict` implementation.

This is probably not expected behaviour.

**Comment by grantjenks** [comment]
Hmmm, shoot, that's certainly a bug. That problem exists for the "viewkeys", "viewvalues", and "viewitems" methods too.

I see a couple options:

1. Set `iteritems`, `iterkeys`, `itervalues` and `viewkeys`, `viewvalues`, `viewitems` to `None` in `SortedDict`. Don't override them, just get rid of them.
2. Implement all six methods but make them only available in Python 2.
3. Maybe it's better to set `viewkeys`, `viewvalues`, and `viewitems` to `None` as those have been replaced by `keys`, `values`, and `items`. But the `iter*` variants should be implemented.

I like (1) because it adopts the semantics of Python 3. But Python 2 is still supported (at least until 2020) so (2) is probably the better choice for now.

Any thoughts?

**Comment by bucko909** [comment]
I don't recommend setting them to `None`: Doing so will be confusing. You could implement `raise NotImplementedError("removed in sortedcontainers>2.0.2")` as an alternative.

The contract of these functions is to return an iterator for the various slices of the object; I think pretty much all developers would be satisfied if the `iterkeys` implementation was simply `return iter(self.keys())` and the `viewkeys` implementation `return self.keys()`. You can choose to add this only in Python 2 and it'll follow the expectation of the users. On Python 3 there's no expectation of existence of these functions, so it's fine to not implement them.

There's a question of whether something that's not a `list` follows the expectation of users calling `keys()`, of course -- if it's not iteration-safe (I didn't check) it may be surprising that `for k in d.keys(): d.pop(k)` might fail, for instance. I'm not too worried myself, as my primary complaint here is only that the misbehaviour is silent.

**Comment by grantjenks** [comment]
I'm leaning toward raising AttributeError to match the semantics of Python 3 with a message to use the `keys`, `values`, or `items` methods instead.

In your example: `for k in d.keys(): d.pop(k)` it unfortunately runs but fails to iterate all keys. There's a disclaimer in the docs at http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html#sortedcontainers.SortedDict.__iter__ about that behavior.

**Comment by grantjenks** [comment]
Committed at 022167c. Deployed to PyPI at v2.0.4
