### ISSUE TITLE
Reverse Compatibility: Python 2.7 and iteritems (et al.)

### ISSUE THREAD

**Issue by matthewphsmith** [grantjenks/python-sortedcontainers#95]
We've been using sortedcontainers on Python 2.7 for a while and making use of iteritems() without issue.  However, the new version is breaking for us.  If the goal is to indicate that the behavior of `sorted_dict.iteritems()` is not the same as `iter(sorted_dict.items())`, shouldn't this be accompanied by a major version increment?  I doubt we're the only ones relying on the fact that sorteddict inherits from dict and thus iteritems() is implemented.

**Comment by grantjenks** [comment]
It was a major version change. If you pin to "<2.0.0" then you'll have the old Python 2 semantics.

The bug was introduced in v2.0.0 and discussed in #94. You can read the release notes at http://www.grantjenks.com/docs/sortedcontainers/history.html and instructions on migrating at http://www.grantjenks.com/docs/sortedcontainers/introduction.html#migrating and get future updates on the Python Announce email list: https://mail.python.org/pipermail/python-announce-list/2018-May/011950.html

**Comment by matthewphsmith** [comment]
Thank you for the prompt response and additional context.  I saw a few of those in my search and we have pinned back to <2.0.0.  I suppose my argument is that this bug fix actually necessitates another major release since it is introducing new breaking behavior (although it is rectifying other breaking behavior).
